---
title: "Creating graphs in R with `ggplot2`"
author: "Sarah McCutcheon"
date: "1/20/2022"
output: html_document
---

#Plots with ggplot2

We are going to make plot sin R and it's going to be amazing.

We use the following data from the Santa Barbara Coastal Term Ecological Research and National  Oceanic and Atmospheric Administration in our analyses

```{r echo=FALSE, message=FALSE}
#Attach packages
library(tidyverse)
library(readxl)
library(here)
```


```{r echo=FALSE, message=FALSE}
ca_np <- read_csv(here("data", "ca_np.csv"))

ci_np <- read_excel(here("data", "ci_np.xlsx"))

```

#Let's make graphs
```{r results='hide'}

ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()

gg_base<- ggplot(data = ci_np, aes(x = year, y = visitors))

gg_base +
  geom_point()

gg_base +
  geom_col()

gg_base +  
  geom_area()

```

#Customize graphs

```{r}

gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
  )

gg_base + 
  geom_point(color = "purple",
             pch = 17,
             size = 4,
             alpha = 0.5)

gg_base +
  geom_col(color = "purple4", fill = "mediumspringgreen")
```

#Mapping variables onto aesthetics

```{r}
gg_base + 
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )

gg_base + 
  geom_col(aes(fill = visitors))
```
